[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "a489d8a5e767f4a6ea5d353047f5833f812d8023"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "7fd4b0533e225ec21e2e1ae52a1ed1397d471a712d1f47179c5df62464062ff1"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "58a810157fe2e178a811213dd8710999b465156c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "b137577ce782cbe71cd3eb49a425cdc8e58a0f91bd81ca4637ebf1a32668afb0"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "b8a2ff05b540ef4587a54e3865efdbc9c93abcd5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "bccc48bdbef2c3ce975ad5637fdf7d0cff6a9a2db6c45d44a0d3afefe7f62168"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.aarch64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b303d48197d4acbd049c1016f727c6bb5ee5bb63"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "9bfc36c101e3d463257a1f7a977101e46d5c8658e776358c688b341dcfef123b"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb01be6754eafe8362429f5eb7a170f95256bd18"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "dc6d5b0f1f478ba6407ff0e6619fd3a8a419af3648ecea384b1f8291b0af031a"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52f61352b9a3f2641cf3f9502910ff51bfd11b32"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "484a5721100362ec3c0a4909daf4bfc679e8e820a5c85dc55d1db2310f02fb32"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45246f4d2a2377fd0aee50672a178359b741a0b9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "fe37fb418494f05638f83c32a546e69c0294b0b3279695e6938e025b1356a41c"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "f4baf951ef5f092d75089eb45baf97190eff90c2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "5704a9b34e87ce72a3412ee2779759ad93772152ac82751f5692a5f777359438"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.i686-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "3b72f009c0e7e0e5c048ee40cb93fe09dd6d7622"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "e39039c0e0968adfe84ba05149188f7e77420084c2388facee126c68259ca00c"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.i686-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "12fbfc7422fd30a379ef21b4713661a45652bef7"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "a679b5d57030f36e9f0a0618376397fb987c9d310442e75d37f21cc052ca4236"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "powerpc64le"
git-tree-sha1 = "761ffb3456b6ba4321bc8622db947a7a0c0de1c4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "9cc8e9acad5d7c563408206ef79ec6a9071bfbb6e873681cce94682919c565ec"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "32cc883218a0151e81ad136fea83b3396de175b8"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "acd412e0f44d13023bbc56c07e29b4db901a9015acf03bb645696fc5e03444e1"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "df2980f7b8a34f74e8a2e0e585e4374a1c06f958"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "a46f9ab1524b0c7a138bcde3ed109fe1ed79d1a316fb8a29403c6229b44110e5"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "cd65371077f5eb3b1f12d189c1cffbb6ec816113"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "e4a5b57506b28006dd880e187da1a1724273b548124d3819c8e3ec605aa69a2c"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.x86_64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "95836bc308cefaea6950c18f8359ad9d5b96e88b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MAGEMin.download]]
    sha256 = "0121bde62eb643ebd938fe7850dbed644a8a6385897cf035056fec9d2a97562b"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "8e051f1ff15c08f56d20a8bac684e3e380df863d"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "ceffce080e5f0823606add723b676a41fd30add796fddf619a5541ca8b770bae"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.4+0/MAGEMin.v2.0.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
