[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "fe13353058114711d64079210a2a3e0b5506ab15"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "e50a2674a1d1f2d30f6978c639a2d3337c0374e7b358824025d0322ad1948e40"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "760e5491b6e5df87535a4b9b18ff28d8b65ddb72"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "a4b8a2c73f088f539b432cd4c8696bfb0727b61f7ed2afa4d6710780c0b8de6a"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "66e646910db60577546b47ba86156d0edb949281"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "f1317f1e9bab0d226670c83ad199b2dfcca9d12df9140b2c77a0c11c50657b4a"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.aarch64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5214a4a17153fd0a1b3bdb3fdb3349d93c648b84"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "e7e6a61bbc502d23ddff2a1f3368d33d8808a2506b53dbb7dbd63fe981f5e6b3"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66f03d632c3db366ca3789be15ceafe12a5df09a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "ea09d7c1281fa8a2df04376b98271bfdad9bc8f1ba5532ef1da69d4c90658360"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31794c2d86843c12e38c09d1be798194e35c74fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "820cab4985e77fe51c1c406432e081ef424930781f7ffc8960dbb4923662a690"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7292839f651c9b9ae21d10fef00545cc661aa24c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "ceca72c104527f65fd7518743f564217d9746752087a4a99f7153b6b6082a9c6"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "5bb4225fc18c43ff985ca478b76fdb324cda2e57"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "4f080dce450ddcf1ae49468be9661e78b03d9a238dbe48ae3b78cb698b232c25"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.i686-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "e2752022fe81a86e39cef3531ab6ca2610c69757"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "440ccc473de8a3b59f0796333d94696d47b72e436397ce91342abe8eceb26785"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.i686-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "ab395ebf2d175a2ba126261a0e346ec4980ec4ba"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "8e6eb2607564baa3600846bd2d7b40cc7f586ad1f65ea34890a82cc4af649f1e"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.i686-w64-mingw32-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "powerpc64le"
git-tree-sha1 = "2398ecd87c969a89dea348da39bee7d0027771a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "cf9d4e2eb97379e94adcd115cc1cf74c38316ed8acd7ad9ce7283f28ffb7aef2"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "5626cb88f1c1c0f96b6bb60a75cb7318a7932d26"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "dc6e52b7ce418d14c6c6f1acb8604de5bebc07b3c6bcf91d9b8bede83eda4895"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "7af7aadf8f7bcf01f0fe4584b48078c35d682357"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "a179f1d14d984c685eeb90b1e797679bd8f6c143abcee38369b255448f71f4b8"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "ed42705c9e1b089cd25c8492e398b7feb7d3221f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "69717cbf74ccbf8beb6470fa809f419ebb0cde5dc3bca9ee3519f1da6e4a42c8"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.x86_64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "feba1d12ce6e5e0ba67ca430866a765d8ba4f712"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MAGEMin.download]]
    sha256 = "269ec291c01a8d92d22cf0369d12bb6f7cb01f88c9bbaf4776fcdcdc7b8c8766"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "4f0ef62f2f24439823456412809bbc4b3531c54d"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "274503fe1bf9972fd6e179667149803a832e76ae4d5619a5da1866c38ba25111"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.9.7+0/MAGEMin.v1.9.7.x86_64-w64-mingw32-libgfortran5.tar.gz"
