[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "d8b393721469bcbfebc8a9837dc54dc918b63260"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "4dba08de243e41882ec7afb20414d6a530b3ac78523046fe18868a96beb2e31a"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "a26cc14901fed52f9acf66ad3001246a8d7d81b9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "67af857e09f3fdf8c0d1f0fbc94a2ec9329517869953cc1b4c77839d950c6a9c"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "0f9db0c4693445b47ab1f441a29a64f5beaf5dc0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "cfe46131e8aabde9f53f0b4f912089dbd61b6958d733c25547e5c4b1b86a9e0d"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0582bc1e3df80254e766127ab8a5c1b598e8de86"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "62ee0e5157a1a4b47129393f23329d9b70e53da778f1187e3678238254893829"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3804c2f2c7ab4678b91a432c76b78187a1b62456"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "3234101475c22f00d33f02dfd1164ae7e2f76f4e09d134630a0bebc77cab93dd"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9bd7d7145d1e7a02c4f4e37afc003828145cc069"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "e24ba0f528dad8d598850c23e6639c123c2366c57410783364201be3443ce8bd"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d5b0c50e80ffe54a4c06da3dee96dcd36a035f56"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "38ce5aba9865aa9dab4f72e1bf81db150988bd238bae49e0e0d16618d2185fc6"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "17995ec782bd0cc984d2ade1f7620d2b957a0810"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "3e47270c6fc12a5f6d21d04a071779d306bf9c3a770c4cd20897dcc0b404ed09"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.i686-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "5da3d1c02126bc2d830036a938af7b0071255f0f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "e5a3969f3c313f2dec0d89f2563988979813c1ab81e5e84d419f21a6bfd4d2c7"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.i686-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "f51f753e56b0118b73161ab1a522eff3b092c861"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "a99d393d9cfb85076459a8a424f5f461822dc9a50482484cc210ca8a190f4c9e"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "powerpc64le"
git-tree-sha1 = "92762fd1eab6f4defe1f3e3521a3568ca8037c0e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "3fd38b2ea88bdebd586e5f27fa5e3c3a5cfba8d26dcb7d87d3a9e8a5f44239c7"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "1a615e29606c9c8617d3c56ad37d3ec18e0d3e67"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "ea9f506efd5c0eccd4de5c39cfce57a0be14de8d4522ebe2d542dbc4323107df"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "4471f3601ba54a2f42d576405638757a03cf5a4b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "0f1015e54a84c3434d5bbd3064601b2f1a51c2b5c550c94ff51f40ebaac027a9"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "746137529fedc3a869caaa02cc67a01d99c70e6a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "54eb971d33bae87a77e0898884832b266d0f2046bb150524c4361d70f3c92c7e"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "3a1d347fa6e02788e7c860440d43f2b7b24ff0bf"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MAGEMin.download]]
    sha256 = "cb752d0709f10bf5df8abd0730216b92f11019936892fc56bd34f3f5d7196fa1"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "484e4571b832a08abbaeab5d8608f9c476e5b339"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "e9804fd7f556a03bb046108a65206b52fd8a8b4cd65f22a572a32bb68840465e"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v2.0.5+0/MAGEMin.v2.0.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
